<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FQ8REV2" failures="0" tests="2" name="Tests.PayCioLoginTest" time="15.021" errors="1" timestamp="2025-04-01T12:48:11 IST" skipped="0">
  <testcase classname="Tests.PayCioLoginTest" name="tearDown" time="0.108">
    <error message="Cannot invoke &quot;pages.PayCioHomePage.clickWelcomeBackButton()&quot; because &quot;this.payciohomepage&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "pages.PayCioHomePage.clickWelcomeBackButton()" because "this.payciohomepage" is null
at pages.BaseTest.tearDown(BaseTest.java:493)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:238)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:223)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:137)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </error>
  </testcase> <!-- tearDown -->
  <testcase classname="Tests.PayCioLoginTest" name="loginScenario" time="14.913">
    <system-out>
      <![CDATA[Clicked the 'Allow' button.
Clicked the 'Skip' button.
✅ Generated Mobile Number: 8299803929
✅ Entered Mobile Number: 8299803929
Clicked the checkbox.
Clicked the 'Get Call' button.
Clicked the 'Allow' button for phone call logs.
Clicked the 'Allow' button for phone call logs.]]>
    </system-out>
  </testcase> <!-- loginScenario -->
  <system-out>
    <![CDATA[Clicked the 'Allow' button.
Clicked the 'Skip' button.
✅ Generated Mobile Number: 8299803929
✅ Entered Mobile Number: 8299803929
Clicked the checkbox.
Clicked the 'Get Call' button.
Clicked the 'Allow' button for phone call logs.
Clicked the 'Allow' button for phone call logs.]]>
  </system-out>
</testsuite> <!-- Tests.PayCioLoginTest -->
